@startuml
participant "User" as u
participant "OpenAPI" as o
participant "RPAs" as r
participant "Cache" as c

autonumber
activate u
u -> o: 提交任务
activate o
o -> c: 获取当前用户所在服务器
activate c
o <-- c: 返回服务器
deactivate c
o -> o: 判断是否已登录
activate o
deactivate o
o -> r: 查询可用客户端数量
activate r
o <-- r: 返回任务可用客户端数量
deactivate r
o -> o: 判断是否存在可用客户端
activate o
deactivate o
o -> c: 缓存用户所在服务器
activate c
o <-- c: 返回结果
deactivate c
o -> r: 提交任务
activate r
o <-- r: 返回任务
deactivate r
u <-- o: 返回任务
deactivate o

@enduml